name: Dispatch build of the freenas-proxmox plugin package

on:
  push:

jobs:
  dispatch:
    name: Dispatch to the build and packager workflow.
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch request to 'freenas-proxmox-packer' repo.
        uses: peter-evans/repository-dispatch@v2
        with:
          #token: ${{ secrets.GITHUB_TOKEN }} 
          repository: eCiceron/freenas-proxmox-packer
          event-type: build_push
          client-payload: '{"ref" : "${{ github.ref }}", "sha": "${{ github.sha }}"}'
